### NumPy Assignment


### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [1]:
import numpy as np

In [2]:
#array with size (5,5) with random integers
array = np.random.randint(1,21,size=(5,5))
print('--- Original Array ---')
print(array)

print('--- After Changing Element at 3rd column ---')

array[:,2] = 1
print(array)

--- Original Array ---
[[ 7 12  3  6 16]
 [ 2 18 18  4 20]
 [ 3  5 12  4 12]
 [13  3 19  1  6]
 [15 17  4 17  1]]
--- After Changing Element at 3rd column ---
[[ 7 12  1  6 16]
 [ 2 18  1  4 20]
 [ 3  5  1  4 12]
 [13  3  1  1  6]
 [15 17  1 17  1]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [3]:
array = np.arange(1,17).reshape((4,4))
print('--- Original Array ---')
print(array)
print('--- After changing diagonal elements ---')
np.fill_diagonal(array,0)
print(array)

--- Original Array ---
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
--- After changing diagonal elements ---
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [4]:
array = np.arange(1,37).reshape((6,6))
print('--- Original Array ---')
print(array)
array[2:5,1:4]

--- Original Array ---
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [6]:
array = np.random.randint(1,21,size=((5,5)))
print('--- Original Array ---')
print(array)
border_elements = np.concatenate((array[0,:],array[-1,:],array[1:-1,0],array[1:-1,-1]))
print('--- Border Elements ---')
print(border_elements)

--- Original Array ---
[[13 19  3  8  3]
 [19  7  9 14 12]
 [ 1  2  1 12 11]
 [ 6 12 14 11 12]
 [15 17  6  9  5]]
--- Border Elements ---
[13 19  3  8  3 15 17  6  9  5 19  1  6 12 11 12]


In [7]:
# Create a NumPy array of shape (5, 5) with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Extract the elements on the border
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements:")
print(border_elements)

Original array:
[[10 15  2 12 11]
 [ 2  4 13  4 12]
 [20 17 14 11 18]
 [ 2  8 16 17 19]
 [ 2 17  1  7 16]]
Border elements:
[10 15  2 12 11  2 17  1  7 16  2 20  2 12 18 19]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [8]:
array1 = np.random.randint(1,11,size=(3,4))
array2 = np.random.randint(1,11,size=(3,4))

print('-- Array1 --')
print(array1)
print('-- Array2 --')
print(array2)

addition = array1+array2
substraction = array1-array2
multiplication = array1*array2
division = array1/array2

print('-- Elementwise addition --')
print(addition)
print('-- Elementwise substraction --')
print(substraction)
print('-- Elementwise multiplication --')
print(multiplication)
print('-- Elementwise division --')
print(division)


-- Array1 --
[[10 10  7  2]
 [ 6 10 10  1]
 [ 6  1  2  9]]
-- Array2 --
[[1 7 2 4]
 [1 8 3 3]
 [7 3 5 6]]
-- Elementwise addition --
[[11 17  9  6]
 [ 7 18 13  4]
 [13  4  7 15]]
-- Elementwise substraction --
[[ 9  3  5 -2]
 [ 5  2  7 -2]
 [-1 -2 -3  3]]
-- Elementwise multiplication --
[[10 70 14  8]
 [ 6 80 30  3]
 [42  3 10 54]]
-- Elementwise division --
[[10.          1.42857143  3.5         0.5       ]
 [ 6.          1.25        3.33333333  0.33333333]
 [ 0.85714286  0.33333333  0.4         1.5       ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [10]:
array = np.arange(1,17).reshape((4,4))
print('-- Original Array --')
print(array)

row_sum = np.sum(array.axis=1)
col_cum = np.sum(array,axis=0)

-- Original Array --
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
