### NumPy Assignment


### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [1]:
import numpy as np

In [2]:
#array with size (5,5) with random integers
array = np.random.randint(1,21,size=(5,5))
print('--- Original Array ---')
print(array)

print('--- After Changing Element at 3rd column ---')

array[:,2] = 1
print(array)

--- Original Array ---
[[11  5 11 11 16]
 [13 12  2 14  6]
 [ 7 19 12 15 15]
 [20  2 11 19  8]
 [ 9 20  9  5  5]]
--- After Changing Element at 3rd column ---
[[11  5  1 11 16]
 [13 12  1 14  6]
 [ 7 19  1 15 15]
 [20  2  1 19  8]
 [ 9 20  1  5  5]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [3]:
array = np.arange(1,17).reshape((4,4))
print('--- Original Array ---')
print(array)
print('--- After changing diagonal elements ---')
np.fill_diagonal(array,0)
print(array)

--- Original Array ---
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
--- After changing diagonal elements ---
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [4]:
array = np.arange(1,37).reshape((6,6))
print('--- Original Array ---')
print(array)
array[2:5,1:4]

--- Original Array ---
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [5]:
array = np.random.randint(1,21,size=((5,5)))
print('--- Original Array ---')
print(array)
border_elements = np.concatenate((array[0,:],array[-1,:],array[1:-1,0],array[1:-1,-1]))
print('--- Border Elements ---')
print(border_elements)

--- Original Array ---
[[11  7  3  2 18]
 [ 8  5 15  4  3]
 [ 2 11 20 20 12]
 [ 5  8 13  3  8]
 [10  5  1 11 11]]
--- Border Elements ---
[11  7  3  2 18 10  5  1 11 11  8  2  5  3 12  8]


In [6]:
# Create a NumPy array of shape (5, 5) with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Extract the elements on the border
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements:")
print(border_elements)

Original array:
[[17 20  7  1 20]
 [ 2 15 17  8 17]
 [10 15 13 13 13]
 [ 8  8 14  8  8]
 [ 9  9 18 14 13]]
Border elements:
[17 20  7  1 20  9  9 18 14 13  2 10  8 17 13  8]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [7]:
array1 = np.random.randint(1,11,size=(3,4))
array2 = np.random.randint(1,11,size=(3,4))

print('-- Array1 --')
print(array1)
print('-- Array2 --')
print(array2)

addition = array1+array2
substraction = array1-array2
multiplication = array1*array2
division = array1/array2

print('-- Elementwise addition --')
print(addition)
print('-- Elementwise substraction --')
print(substraction)
print('-- Elementwise multiplication --')
print(multiplication)
print('-- Elementwise division --')
print(division)


-- Array1 --
[[3 2 9 1]
 [8 1 9 1]
 [9 5 8 2]]
-- Array2 --
[[4 1 7 8]
 [6 2 3 9]
 [3 4 3 6]]
-- Elementwise addition --
[[ 7  3 16  9]
 [14  3 12 10]
 [12  9 11  8]]
-- Elementwise substraction --
[[-1  1  2 -7]
 [ 2 -1  6 -8]
 [ 6  1  5 -4]]
-- Elementwise multiplication --
[[12  2 63  8]
 [48  2 27  9]
 [27 20 24 12]]
-- Elementwise division --
[[0.75       2.         1.28571429 0.125     ]
 [1.33333333 0.5        3.         0.11111111]
 [3.         1.25       2.66666667 0.33333333]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [8]:
array = np.arange(1,17).reshape((4,4))
print('-- Original Array --')
print(array)

row_sum = np.sum(array,axis=1)
col_cum = np.sum(array,axis=0)

print('-- Rowwise sum --')
print(row_sum)
print('-- Colwise sum --')
print(col_cum)

-- Original Array --
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
-- Rowwise sum --
[10 26 42 58]
-- Colwise sum --
[28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [9]:
array = np.random.randint(1,21,size=(5,5))
print('-- Original Array --')
print(array)

mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
var = np.var(array)

print('-- Mean --')
print(mean)
print('-- Median --')
print(median)
print('-- Standard Deviation --')
print(std_dev)
print('-- Variance --')
print(var)

-- Original Array --
[[ 9  6 18  1  4]
 [15 13 13 19  5]
 [17  4 12  7 12]
 [ 4 20 12 15 11]
 [16 17  5 12 19]]
-- Mean --
11.44
-- Median --
12.0
-- Standard Deviation --
5.506941074680207
-- Variance --
30.3264


Mean: it calculates the mean of all 25 elements in the array — not row-wise or column-wise, just a single average of everything.  
Median: The median is the middle value in a sorted list.  
- If there’s an odd number of elements → it's the center one.
- If there’s an even number → it's the average of the two middle values.  
Standard deviation measures how spread out the numbers are from the mean.



2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [11]:
# Create the original array

array = np.arange(1,10).reshape((3,3))
print('-- Original Array --')
print(array)

#normalize the array
mean = np.mean(array)
std_dev = np.std(array)
normalized_arr = (array-mean)/std_dev

print('-- Normalised array --')
print(normalized_arr)

-- Original Array --
[[1 2 3]
 [4 5 6]
 [7 8 9]]
-- Normalised array --
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [13]:
#create a original array
array = np.random.randint(1,11, size=(3,3))
row_array = np.random.randint(1,11,size=(3,))

print('-- Original array --')
print(array)
print('-- 1D array --')
print(row_array)

#Add the 1D array to each array using broadcasting
result = array + row_array
print('-- Resulted array --')
print(result)


-- Original array --
[[ 9  8  2]
 [ 4  2  7]
 [ 6  4 10]]
-- 1D array --
[4 4 2]
-- Resulted array --
[[13 12  4]
 [ 8  6  9]
 [10  8 12]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [16]:
#create the original array
array = np.random.randint(1,17,size=(4,4))
row_array = np.random.randint(1,17,size=(4,))
print('-- Original array --')
print(array)
print('-- Row array')
print(row_array)

#substract 1D array from each column of the 2D array using broadcasting
result = array - row_array
print('-- Resulted array --')
print(result)

-- Original array --
[[11  7 10 16]
 [ 7  1  2  2]
 [ 6 12 15 10]
 [10 16  6  7]]
-- Row array
[11 10  1  6]
-- Resulted array --
[[ 0 -3  9 10]
 [-4 -9  1 -4]
 [-5  2 14  4]
 [-1  6  5  1]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [20]:
#create the matrix with the size (3,3)
matrix = np.random.randint(1,11,size=(3,3))
print('-- Matrix --')
print(matrix)

#calculate its determinant
determinant = np.linalg.det(matrix)
print(f'Determinant: {determinant}')

#calculate the Inverse
inverse = np.linalg.inv(matrix)
print(f'Inverse: {inverse}')

#calculate the Eigen values
eigenvalues = np.linalg.eigvals(matrix)
print(f'Eigen values: {')

-- Matrix --
[[ 1  4  8]
 [ 1  7 10]
 [ 4  6  7]]
Determinant: -55.000000000000014
Inverse: [[ 0.2        -0.36363636  0.29090909]
 [-0.6         0.45454545  0.03636364]
 [ 0.4        -0.18181818 -0.05454545]]
