### NumPy Assignment


### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [1]:
import numpy as np

In [2]:
#array with size (5,5) with random integers
array = np.random.randint(1,21,size=(5,5))
print('--- Original Array ---')
print(array)

print('--- After Changing Element at 3rd column ---')

array[:,2] = 1
print(array)

--- Original Array ---
[[ 7 12  3  6 16]
 [ 2 18 18  4 20]
 [ 3  5 12  4 12]
 [13  3 19  1  6]
 [15 17  4 17  1]]
--- After Changing Element at 3rd column ---
[[ 7 12  1  6 16]
 [ 2 18  1  4 20]
 [ 3  5  1  4 12]
 [13  3  1  1  6]
 [15 17  1 17  1]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [3]:
array = np.arange(1,17).reshape((4,4))
print('--- Original Array ---')
print(array)
print('--- After changing diagonal elements ---')
np.fill_diagonal(array,0)
print(array)

--- Original Array ---
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
--- After changing diagonal elements ---
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [4]:
array = np.arange(1,37).reshape((6,6))
print('--- Original Array ---')
print(array)
array[2:5,1:4]

--- Original Array ---
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [5]:
array = np.random.randint(1,21,size=((5,5)))
print('--- Original Array ---')
print(array)
border_elements = np.concatenate()

--- Original Array ---
[[13  3 10  7 10]
 [ 5 16 18 17  5]
 [17  3  4 12  8]
 [ 6 13  3 18  5]
 [19 14 13  4  1]]
