### NumPy Assignment


### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [2]:
import numpy as np

In [4]:
#array with size (5,5) with random integers
array = np.random.randint(1,21,size=(5,5))
print('Original Array')
print(array)

Original Array
[[ 2  5  1 16  6]
 [19  2 14 14  5]
 [ 2  7 13 19 15]
 [16 13 13  5  5]
 [10 12 16 13 18]]


In [5]:
array[:,2] = 1
print(array)

[[ 2  5  1 16  6]
 [19  2  1 14  5]
 [ 2  7  1 19 15]
 [16 13  1  5  5]
 [10 12  1 13 18]]
