### NumPy Assignment


### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [1]:
import numpy as np

In [2]:
#array with size (5,5) with random integers
array = np.random.randint(1,21,size=(5,5))
print('--- Original Array ---')
print(array)

print('--- After Changing Element at 3rd column ---')

array[:,2] = 1
print(array)

--- Original Array ---
[[12 18  1 17 10]
 [20 12 20  9 11]
 [ 4 17 12 13 19]
 [ 3  1  8 14 18]
 [20 15  6  1  5]]
--- After Changing Element at 3rd column ---
[[12 18  1 17 10]
 [20 12  1  9 11]
 [ 4 17  1 13 19]
 [ 3  1  1 14 18]
 [20 15  1  1  5]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [3]:
array = np.arange(1,17).reshape((4,4))
print('--- Original Array ---')
print(array)
print('--- After changing diagonal elements ---')
np.fill_diagonal(array,0)
print(array)

--- Original Array ---
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
--- After changing diagonal elements ---
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [4]:
array = np.arange(1,37).reshape((6,6))
print('--- Original Array ---')
print(array)
array[2:5,1:4]

--- Original Array ---
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [5]:
array = np.random.randint(1,21,size=((5,5)))
print('--- Original Array ---')
print(array)
border_elements = np.concatenate((array[0,:],array[-1,:],array[1:-1,0],array[1:-1,-1]))
print('--- Border Elements ---')
print(border_elements)

--- Original Array ---
[[ 3  5 17 17  3]
 [ 2  7  8 15 10]
 [ 7 15 14 15  8]
 [ 1  5 16  5  9]
 [16  3 20  9  6]]
--- Border Elements ---
[ 3  5 17 17  3 16  3 20  9  6  2  7  1 10  8  9]


In [6]:
# Create a NumPy array of shape (5, 5) with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Extract the elements on the border
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements:")
print(border_elements)

Original array:
[[12  1 11  2 15]
 [ 6  5  6 19 11]
 [14  7 16 18  6]
 [ 9 20 10  1  6]
 [ 1 16  3  7 11]]
Border elements:
[12  1 11  2 15  1 16  3  7 11  6 14  9 11  6  6]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [7]:
array1 = np.random.randint(1,11,size=(3,4))
array2 = np.random.randint(1,11,size=(3,4))

print('-- Array1 --')
print(array1)
print('-- Array2 --')
print(array2)

addition = array1+array2
substraction = array1-array2
multiplication = array1*array2
division = array1/array2

print('-- Elementwise addition --')
print(addition)
print('-- Elementwise substraction --')
print(substraction)
print('-- Elementwise multiplication --')
print(multiplication)
print('-- Elementwise division --')
print(division)


-- Array1 --
[[ 9  8 10  8]
 [ 4  9  1  9]
 [ 2  5  1  5]]
-- Array2 --
[[5 6 1 4]
 [3 3 1 5]
 [6 9 6 5]]
-- Elementwise addition --
[[14 14 11 12]
 [ 7 12  2 14]
 [ 8 14  7 10]]
-- Elementwise substraction --
[[ 4  2  9  4]
 [ 1  6  0  4]
 [-4 -4 -5  0]]
-- Elementwise multiplication --
[[45 48 10 32]
 [12 27  1 45]
 [12 45  6 25]]
-- Elementwise division --
[[ 1.8         1.33333333 10.          2.        ]
 [ 1.33333333  3.          1.          1.8       ]
 [ 0.33333333  0.55555556  0.16666667  1.        ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [8]:
array = np.arange(1,17).reshape((4,4))
print('-- Original Array --')
print(array)

row_sum = np.sum(array,axis=1)
col_cum = np.sum(array,axis=0)

print('-- Rowwise sum --')
print(row_sum)
print('-- Colwise sum --')
print(col_cum)

-- Original Array --
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
-- Rowwise sum --
[10 26 42 58]
-- Colwise sum --
[28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [9]:
array = np.random.randint(1,21,size=(5,5))
print('-- Original Array --')
print(array)

mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
var = np.var(array)

print('-- Mean --')
print(mean)
print('-- Median --')
print(median)
print('-- Standard Deviation --')
print(std_dev)
print('-- Variance --')
print(var)

-- Original Array --
[[ 1  7 12 13 12]
 [12  9 20 15 15]
 [ 5  4 20  9  4]
 [20 10  2 20  7]
 [ 5  1  1  6 20]]
-- Mean --
10.0
-- Median --
9.0
-- Standard Deviation --
6.437390775772433
-- Variance --
41.44


Mean: it calculates the mean of all 25 elements in the array — not row-wise or column-wise, just a single average of everything.  
Median: The median is the middle value in a sorted list.  
- If there’s an odd number of elements → it's the center one.
- If there’s an even number → it's the average of the two middle values.  
Standard deviation measures how spread out the numbers are from the mean.



2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [10]:
# Create the original array

array = np.arange(1,10).reshape((3,3))
print('-- Original Array --')
print(array)

#normalize the array
mean = np.mean(array)
std_dev = np.std(array)
normalized_arr = (array-mean)/std_dev

print('-- Normalised array --')
print(normalized_arr)

-- Original Array --
[[1 2 3]
 [4 5 6]
 [7 8 9]]
-- Normalised array --
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [11]:
#create a original array
array = np.random.randint(1,11, size=(3,3))
row_array = np.random.randint(1,11,size=(3,))

print('-- Original array --')
print(array)
print('-- 1D array --')
print(row_array)

#Add the 1D array to each array using broadcasting
result = array + row_array
print('-- Resulted array --')
print(result)


-- Original array --
[[ 5  3  6]
 [ 2 10  8]
 [ 4  5  4]]
-- 1D array --
[9 7 1]
-- Resulted array --
[[14 10  7]
 [11 17  9]
 [13 12  5]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [12]:
#create the original array
array = np.random.randint(1,17,size=(4,4))
row_array = np.random.randint(1,17,size=(4,))
print('-- Original array --')
print(array)
print('-- Row array')
print(row_array)

#substract 1D array from each column of the 2D array using broadcasting
result = array - row_array
print('-- Resulted array --')
print(result)

-- Original array --
[[16 10  4  9]
 [11  2  3  4]
 [ 5  4  5 16]
 [15  8  2  5]]
-- Row array
[ 3  1  9 16]
-- Resulted array --
[[ 13   9  -5  -7]
 [  8   1  -6 -12]
 [  2   3  -4   0]
 [ 12   7  -7 -11]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [13]:
#create the matrix with the size (3,3)
matrix = np.random.randint(1,11,size=(3,3))
print('-- Matrix --')
print(matrix)

#calculate its determinant
determinant = np.linalg.det(matrix)
print(f'Determinant: {determinant}')

#calculate the Inverse
inverse = np.linalg.inv(matrix)
print(f'Inverse: {inverse}')

#calculate the Eigen values
eigenvalues = np.linalg.eigvals(matrix)
print(f'Eigen values: {eigenvalues}')

-- Matrix --
[[7 3 9]
 [2 7 3]
 [5 2 8]]
Determinant: 68.00000000000001
Inverse: [[ 0.73529412 -0.08823529 -0.79411765]
 [-0.01470588  0.16176471 -0.04411765]
 [-0.45588235  0.01470588  0.63235294]]
Eigen values: [15.62094469  0.77706898  5.60198633]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [14]:
#create two arrays
array1 = np.random.randint(1,11,size=(2,3))
array2 = np.random.randint(1,11,size=(3,2))

print('Array1')
print(array1)
print('Array2')
print(array2)

#perform matrix multiplication
matrix_multiplication = np.dot(array1,array2)
print('Matrix Multiplication')
print(matrix_multiplication)


Array1
[[7 6 7]
 [3 6 9]]
Array2
[[2 6]
 [7 1]
 [8 4]]
Matrix Multiplication
[[112  76]
 [120  60]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [15]:
#create the array of (3,3)
array = np.arange(1,10).reshape(3,3)
print('Original array')
print(array)

#reshape this array to (1,9)
reshaped_array1 = array.reshape(1,9)
print('Reshaped array 1')
print(reshaped_array1)

#again reshape to array(9,1)
reshaped_array2 = reshaped_array1.reshape(9,1)
print('Reshaped array 2')
print(reshaped_array2)

Original array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped array 1
[[1 2 3 4 5 6 7 8 9]]
Reshaped array 2
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [16]:
#create the array of size (5,5)
array = np.random.randint(1,21,size=(5,5))
print('Original array')
print(array)

#flatten the array
flatten = array.flatten()

print('Flattened array')
print(flatten)

#again reshape to (5,5)
reshaped_array = flatten.reshape(5,5)
print('Reshaped array')
print(reshaped_array)

Original array
[[14 11 10  9 14]
 [16  6 16 20 15]
 [16 10  7 11  2]
 [18  8 17 13  5]
 [13 20 13  3 13]]
Flattened array
[14 11 10  9 14 16  6 16 20 15 16 10  7 11  2 18  8 17 13  5 13 20 13  3
 13]
Reshaped array
[[14 11 10  9 14]
 [16  6 16 20 15]
 [16 10  7 11  2]
 [18  8 17 13  5]
 [13 20 13  3 13]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [17]:
#create an array of (5,5)
array = np.random.randint(1,21,size=(5,5))
print('Original array')
print(array)

#extract elements using fancy indexing
corner_elements = array[[0,0,-1,-1],[0,-1,0,-1]]
print('Corner elements')
print(corner_elements)

Original array
[[11 11  8 13 20]
 [ 2 18 14  2 10]
 [11  7 11 15  1]
 [19 12 14 10  1]
 [ 9 10 20 19 20]]
Corner elements
[11 20  9 20]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [18]:
# create a numpy array of (4,4) with random integers.
array = np.random.randint(1,21,size=(4,4))
print('Original Array')
print(array)

#use boolean indexing to set elements >10 to 10
array[array >10] = 10
print('Modified Array')
print(array)

Original Array
[[20 13 17 18]
 [ 8 11 12 19]
 [13  5 18  3]
 [13 14  9 14]]
Modified Array
[[10 10 10 10]
 [ 8 10 10 10]
 [10  5 10  3]
 [10 10  9 10]]


array > 10  
This creates a boolean mask — an array of the same shape where each element is either True or False, depending on whether the condition is met.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [19]:
# Define the structured array.
data_type = [('name','U10'),('age','i4'),('weight','f4')]
array = np.array([('ganesh',34,70.1),('dilip',33,65.2),('amol',23,80.3)],dtype=data_type)
print('Original Array')
print(array)

print('-- Sort the array by age --')
sorted_array = np.sort(array,order='age')
print(sorted_array)


Original Array
[('ganesh', 34, 70.1) ('dilip', 33, 65.2) ('amol', 23, 80.3)]
-- Sort the array by age --
[('amol', 23, 80.3) ('dilip', 33, 65.2) ('ganesh', 34, 70.1)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

Using broadcasting to compute pairwise differences and apply the Euclidean formula:

$$
\text{distance} = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}
$$


In [ ]:
# create a structured array with fields x and y.
data_type = [('x','i4'),('y','i4')]
data = np.array()