### NumPy Assignment


### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [2]:
import numpy as np

In [9]:
#array with size (5,5) with random integers
array = np.random.randint(1,21,size=(5,5))
print('--- Original Array ---')
print(array)

print('--- After Changing Element at 3rd column ---')

array[:,2] = 1
print(array)

--- Original Array ---
[[ 1  5 12  5 19]
 [18  6 14  2 18]
 [12  4 13 17 13]
 [ 4 16 18 20  6]
 [16  7  6  5  9]]
--- After Changing Element at 3rd column ---
[[ 1  5  1  5 19]
 [18  6  1  2 18]
 [12  4  1 17 13]
 [ 4 16  1 20  6]
 [16  7  1  5  9]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [12]:
array = np.arange(1,17).reshape((4,4))
print('--- Original Array ---')
print(array)
print('--- After changing diagonal elements ---')
np.fill_diagonal(array,0)
print(array)

--- Original Array ---
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
--- After changing diagonal elements ---
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]
